from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from blueprints.get_response import get_user_info, get_system_message
import openai, sqlite3

# This blueprint handles the workout plans generated by the ai

workout = Blueprint('workout', __name__, template_folder='templates')

@workout.route('/workout_generate')
@login_required
def generate_workout_plan():

    user_info = get_user_info() # Loads the user info from the database
    system_message = get_system_message()

    workout_generate_prompt = f"""  I have a user with the following details: {system_message}.
                                    create a workout plan for them to help them achieve their goal.
                                    depending on their body type, formulate a workout plan that will help them achieve their goal.
                               """
    
    res = openai.ChatCompletion.create(
        model="gpt-4-1106-preview",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "system", "content": workout_generate_prompt}
        ]
    )

    workout_plan = res['choices'][0]['message']['content']  # Extracting the workout plan from the response

    return render_template('workout_plans.html', workout_plan=workout_plan)